/** Central route table — the only place paths are spelled out. */
export const routes = {
  home: '/',
  patientLogin: '/login',
  staffLogin: '/staff/login',
  portal: {
    root: '/me',
    results: '/me/results',
    result: (id = ':documentId') => `/me/results/${id}`,
    visits: '/me/visits',
    visit: (id = ':orderId') => `/me/visits/${id}`,
    profile: '/me/profile',
  },
  app: {
    root: '/app',
    reception: '/app/reception',
    order: (id = ':orderId') => `/app/reception/orders/${id}`,
    patients: '/app/patients',
    patient: (id = ':patientId') => `/app/patients/${id}`,
    orders: '/app/orders',
    lab: '/app/lab',
    labItem: (id = ':itemId') => `/app/lab/${id}`,
    confirm: '/app/confirm',
    reports: '/app/reports',
    messages: '/app/messages',
  },
  admin: {
    root: '/admin',
    company: '/admin/company',
    branches: '/admin/branches',
    employees: '/admin/employees',
    employee: (id = ':employeeId') => `/admin/employees/${id}`,
    roles: '/admin/roles',
    catalog: '/admin/catalog',
    schemas: '/admin/schemas',
    schema: (id = ':schemaId') => `/admin/schemas/${id}`,
    templates: '/admin/templates',
    template: (id = ':templateId') => `/admin/templates/${id}`,
    sms: '/admin/sms',
    platform: '/admin/platform',
  },
} as const
